package com.healthcare.payment.entity;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "payments")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String paymentId;          // UUID generated by us

    @Column(nullable = false)
    private Long appointmentId;

    @Column(nullable = false)
    private Long patientId;

    @Column(nullable = false)
    private BigDecimal amount;

    @Column(nullable = false)
    private String currency;            // LKR / USD

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentMethod method;       // PAYHERE, STRIPE, PAYPAL

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus status;

    private String transactionReference; // Gateway reference (order_id from PayHere)

    private String merchantOrderId;      // Our order id sent to PayHere

    private String gatewayResponse;      // Raw callback data (stored as JSON string)

    private LocalDateTime createdAt;

    private LocalDateTime paidAt;

    private String receiptUrl;           // Generated receipt URL

    private String failureReason;

    // Denormalized fields for invoice generation
    private String patientName;
    private String patientEmail;
    private Long doctorId;
    private String doctorName;
    private String doctorSpecialization;
    private LocalDateTime appointmentDate;
    private String consultationType;      // VIDEO / PHYSICAL
    private BigDecimal consultationFee;   // Doctor's consultation fee
    private BigDecimal serviceFee;        // Platform service fee

    @PrePersist
    public void prePersist() {
        if (createdAt == null) createdAt = LocalDateTime.now();
        if (status == null) status = PaymentStatus.PENDING;
        if (currency == null) currency = "LKR";
    }
}
