services:
  postgres:
    image: 'postgres:latest'
    container_name: synapscare-postgres-doctor
    environment:
      - 'POSTGRES_DB=synapscare_doctors'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - healthcare-network

  doctor-service:
    build: .
    container_name: synapscare-doctor-service
    ports:
      - '8082:8082'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/synapscare_doctors'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
      - 'SPRING_APPLICATION_NAME=doctor-service'
      - 'SPRING_RABBITMQ_HOST=rabbitmq'
      - 'SPRING_RABBITMQ_PORT=5672'
      - 'SPRING_RABBITMQ_USERNAME=admin'
      - 'SPRING_RABBITMQ_PASSWORD=admin123'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - healthcare-network
    restart: unless-stopped

networks:
  healthcare-network:
    driver: bridge
