server:
  port: 8081

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost};instanceName=SQLEXPRESS;databaseName=healthcare_app;encrypt=true;trustServerCertificate=true;
    username: ${DB_USER:sa}
    password: ${DB_PASS:StrongPass!123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
