server:
  port: 8083

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/hospital_system
    username: ${DB_USER:postgres}
    password: ${DB_PASS:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect