server:
  port: 8084

spring:
  application:
    name: integration-service
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:1433;databaseName=integrationdb;encrypt=true;trustServerCertificate=true;
    username: ${DB_USER:sa}
    password: ${DB_PASS:StrongPass!123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
