server:
  port: 8085

spring:
  application:
    name: integration-service
  datasource:
    url: jdbc:postgresql://localhost:5432/synapscare
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

api:
  openrouter:
    key: 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
    url: https://openrouter.ai/api/v1/chat/completions
  payhere:
    merchant-id: 1233989
    secret: MzYzNDIwNTQyNTMyNTUwNDU4MTM0MjMyMzM1NjI4MTIzNjQ2Mjg0Nw==
